package nl.denkzelf.testing123;

public enum TokenType {
    UNKNOWN,
    SEPARATOR,
    STRING,
    CHARACTER,
    IDENTIFIER,
    SINGLELINECOMMENT,
    MULTILINECOMMENT,
    KEYWORD,
    CONTEXTUALKEYWORD,
    OPERATOR,
    DECIMALINTEGERLITERAL,
    DECIMALFLOATINGPOINTLITERAL,
    NUMBER,
    TEXTBLOCK,
    EOF
}
